### ISSUE TITLE
Template exception error

### ISSUE THREAD

**Issue by mclearc** [ebullient/ttrpg-convert-cli#124]
Hi -- it looks like there are further template issues when using the TTRPG statblock templates. I'm getting versions of the following:

```
io.quarkus.qute.TemplateException: Rendering error: Property "description" not found on the base object "dev.ebullient.convert.tools.dnd5e.qute.QuteBackground" in expression {resource.description}
```
This happens with basically any conversion from 5etools JSON with a TTRPG statblock template. 
Unfortunately I am completely new to quarkus, et. al, so I'm not sure how to proceed. If there is further info you need from me please just let me know.

**Comment by ebullient** [comment]
No worries.. please be clear about which version of the cli you're using (release or building yourself), and which templates you're using, etc.

The closer you can get me to reproducing your steps, the better. :)

**Comment by mclearc** [comment]
Hi - these are all the cli and templates from the master branch as of yesterday. I found that I was getting exceptions/errors using any of the statblock templates that used the ttrpg statblock or that used the diceroller. __Colin McLearcolinmclear.netOn May 4, 2023, at 12:47 PM, Erin Schnabel ***@***.***> wrote:﻿
No worries.. please be clear about which version of the cli you're using (release or building yourself), and which templates you're using, etc.
The closer you can get me to reproducing your steps, the better. :)

**Comment by mclearc** [comment]
Nope tried the most recent release of the cli with templates from the feb 16 branch of the repo and still getting the same errors.

**Comment by mclearc** [comment]
Just to give some more info...

I built the current master (I'm on the current version of MacOS) and tried building a compendium using 5etools mirror downloaded yesterday and the `monster2md-yamlStatblock-body.txt` template. I got the following:

```
io.quarkus.qute.TemplateException
	at io.quarkus.qute.CompletedStage.get(CompletedStage.java:48)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5(TemplateImpl.java:239)
	at io.quarkus.qute.CompletedStage.whenComplete(CompletedStage.java:268)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:233)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout(TemplateImpl.java:224)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.render(TemplateImpl.java:149)
	at dev.ebullient.convert.io.Templates.render(Templates.java:62)
	at dev.ebullient.convert.io.Templates_ClientProxy.render(Unknown Source)
	at dev.ebullient.convert.io.MarkdownWriter.doWrite(MarkdownWriter.java:86)
	at dev.ebullient.convert.io.MarkdownWriter.writeFiles(MarkdownWriter.java:66)
	at dev.ebullient.convert.tools.dnd5e.Json2MarkdownConverter.writeFiles(Json2MarkdownConverter.java:85)
	at dev.ebullient.convert.tools.dnd5e.Json2MarkdownConverter.writeAll(Json2MarkdownConverter.java:34)
	at dev.ebullient.convert.tools.dnd5e.Json2MarkdownConverter.writeAll(Json2MarkdownConverter.java:22)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:243)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:252)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:272)
	at dev.ebullient.convert.RpgDataConvertCli_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.quarkus.qute.TemplateException: Rendering error: Property "description" not found on the base object "dev.ebullient.convert.tools.dnd5e.qute.QuteBackground" in expression {resource.description}
	at io.quarkus.qute.TemplateException$Builder.build(TemplateException.java:169)
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:247)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:201)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolve$4(EvaluatorImpl.java:211)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:208)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolve$4(EvaluatorImpl.java:211)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:208)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:128)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolveReference$2(EvaluatorImpl.java:132)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:132)
	at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:87)
	at io.quarkus.qute.ResolutionContextImpl.evaluate(ResolutionContextImpl.java:29)
	at io.quarkus.qute.IfSectionHelper$OperandCondition.evaluate(IfSectionHelper.java:249)
	at io.quarkus.qute.IfSectionHelper$SingletonContext.resolve(IfSectionHelper.java:64)
	at io.quarkus.qute.IfSectionHelper.resolve(IfSectionHelper.java:45)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:223)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1247)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
```
If this is user error apologies in advance. I should note that if I just run the cli without referencing any template in my config it builds without any errors (or at least no errors from the cli tool). So perhaps there is some change in the way resources are handled or named in the monster templates and in the default built in templates in src/main/...?

**Comment by mclearc** [comment]
At the risk of too much info...

Here's my config:

```json
{
  "from": [
    "BAM",
    "CoS",
    "DMG",
    "LoX",
    "MCV1SC",
    "MM",
    "MPMM",
    "MTF",
    "PHB",
    "SAiS",
    "SJA",
    "TCE",
    "VGM",
    "VRGR",
    "XGE"
  ],
  "paths": {
    "compendium" : "2. Mechanics/compendium/",
    "rules" : "2. Mechanics/compendium/rules/"
  },
  "useDiceRoller" : true,
  "full-source" : {
    "book" : [
      "PHB",
      "DMG",
      "MM",
      "TCE",
      "MPMM",
      "XGE",
      "BAM",
      "VRGR",
      "VGM"
    ],
    "adventure" : [
      "LoX",
      "SJA"
    ]
  }
}
The newly built version works with the dice roller
Image
but if I add the template...

{
  "from": [
    "BAM",
    "CoS",
    "DMG",
    "LoX",
    "MCV1SC",
    "MM",
    "MPMM",
    "MTF",
    "PHB",
    "SAiS",
    "SJA",
    "TCE",
    "VGM",
    "VRGR",
    "XGE"
  ],
  "paths": {
    "compendium" : "2. Mechanics/compendium/",
    "rules" : "2. Mechanics/compendium/rules/"
  },
    "template": {
    "background": "/Users/roambot/bin/source-ttrpg-convert/5e-test/monster2md-yamlStatblock-body.txt"
  },
  "useDiceRoller" : true,
  "full-source" : {
    "book" : [
      "PHB",
      "DMG",
      "MM",
      "TCE",
      "MPMM",
      "XGE",
      "BAM",
      "VRGR",
      "VGM"
    ],
    "adventure" : [
      "LoX",
      "SJA"
    ]
  }
}
```
Without a template specified things work well, including the dice roller.  But with the above things go poorly...

The central error being: Caused by: io.quarkus.qute.TemplateException: Rendering error: Property "description" not found on the base object "dev.ebullient.convert.tools.dnd5e.qute.QuteBackground" in expression {resource.description}
I assume the problem lies in the QuteMonster.java file, in  the get5eStatblockYaml block (lines 205-51)  but I can't be sure.

**Comment by mclearc** [comment]
It looks like I've resolved this. The problem seems to be that I was using the wrong "key" to pick out the relevant template. This seems like something that could be clarified in the README (I'd be happy to open a pull request if you'd like).
