### ISSUE TITLE
[FR]: Include images in adventure/book export

### ISSUE THREAD

**Issue by TehMightyPotato** [ebullient/ttrpg-convert-cli#147]
Hey,
as the title suggests I think it would be cool if exported adventures and books included images in them. 

Since most adventures contain maps of some kind and you kind of need them to play (since the book actually references locations on the maps) you would need to manually add them to every adventure page after it has been exported for the exported markdown to be useful.

Is this something that you would consider implementing or can you already do this with the templating engine?

**Comment by ebullient** [comment]
Working on it.

**Comment by TehMightyPotato** [comment]
That was fast. Thanks!

**Comment by ebullient** [comment]
Resolved by 43867ad3e9aa2d5f26c59575db2e470243969547

Try the snapshot? https://github.com/ebullient/ttrpg-convert-cli#use-java-jar

**Comment by TehMightyPotato** [comment]
I will once I've got the time to do so. Thanks a bunch!

**Comment by mclearc** [comment]
I just rebuilt and pulled some books. Looks amazing! 🥳 Thank you!! 🙏

**Comment by ebullient** [comment]
Note additional admonition type (gallery) here: 

https://github.com/ebullient/ttrpg-convert-cli/blob/4bbec3aca77c9e2ee8f2ce0bc3b0e33f1955f05e/examples/admonitions-5e.json


And updated styles for center/right/gallery:
https://github.com/ebullient/ttrpg-convert-cli/blob/main/examples/css-snippets/dnd5e-compendium.css

**Comment by TehMightyPotato** [comment]
Unfortunately the cli crashes for me when running it with my setup that worked before. Looks like it breaks while while processing the images in my template. I included the log and one of the templates that causes the crash below.

Before updating to the snapshot version I was running 2.01, just FYI.

<details><summary>Exception</summary>
<p>

```
io.quarkus.qute.TemplateException
        at io.quarkus.qute.CompletedStage.get(CompletedStage.java:48)
        at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
        at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5(TemplateImpl.java:233)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:227)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout(TemplateImpl.java:218)
        at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.render(TemplateImpl.java:143)
        at dev.ebullient.convert.io.Templates.render(Templates.java:69)
        at dev.ebullient.convert.io.Templates_ClientProxy.render(Unknown Source)
        at dev.ebullient.convert.io.MarkdownWriter.doWrite(MarkdownWriter.java:86)
        at dev.ebullient.convert.io.MarkdownWriter.writeFiles(MarkdownWriter.java:66)
        at dev.ebullient.convert.tools.dnd5e.Json2MarkdownConverter.writeFiles(Json2MarkdownConverter.java:85)
        at dev.ebullient.convert.tools.dnd5e.Json2MarkdownConverter.writeAll(Json2MarkdownConverter.java:34)
        at dev.ebullient.convert.tools.dnd5e.Json2MarkdownConverter.writeAll(Json2MarkdownConverter.java:22)
        at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:230)
        at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:239)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:259)
        at dev.ebullient.convert.RpgDataConvertCli_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:130)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.quarkus.qute.TemplateException: Rendering error: Property "title" not found on the base object "dev.ebullient.convert.qute.ImageRef" in expression {first.title}
        at io.quarkus.qute.TemplateException$Builder.build(TemplateException.java:169)
        at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:247)
        at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:201)
        at io.quarkus.qute.EvaluatorImpl.lambda$resolve$4(EvaluatorImpl.java:211)
        at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
        at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:208)
        at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:128)
        at io.quarkus.qute.EvaluatorImpl.lambda$resolveReference$2(EvaluatorImpl.java:132)
        at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
        at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:132)
        at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:87)
        at io.quarkus.qute.ResolutionContextImpl$ChildResolutionContext.evaluate(ResolutionContextImpl.java:87)
        at io.quarkus.qute.ExpressionNode.resolve(ExpressionNode.java:34)
        at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:223)
        at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:56)
        at io.quarkus.qute.SetSectionHelper.lambda$resolve$1(SetSectionHelper.java:49)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
        at io.quarkus.qute.SetSectionHelper.resolve(SetSectionHelper.java:44)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
        at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:219)
        at io.quarkus.qute.IfSectionHelper$SingletonContext.lambda$resolve$0(IfSectionHelper.java:68)
        at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
        at io.quarkus.qute.IfSectionHelper$SingletonContext.resolve(IfSectionHelper.java:64)
        at io.quarkus.qute.IfSectionHelper.resolve(IfSectionHelper.java:45)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
        at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:223)
        at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
        at io.quarkus.qute.Parser$1.resolve(Parser.java:1247)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
        at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
        ... 27 more
```

</p>
</details> 


<details><summary>Offending Template</summary>
<p>

    ---
    obsidianUIMode: preview
    cssclass: json5e-monster
    statblock: inline
    statblock-link: "#^statblock"
    {#if resource.tags }
    tags:
    {#for tag in resource.tags}
    - {tag}
    {/for}
    {/if}
    aliases: ["{resource.name}"]
    ---
    # {resource.name}
    *Source: {resource.source}*  
    
    {#if resource.description }
    {resource.description}
    
    {#each resource.fluffImages}{#if it_index != 0 }
    ![{it.title}]({it.vaultPath}#center)  
    {/if}{/each}
    {#else}
    {#each resource.fluffImages}
    ![{it.title}]({it.vaultPath}#center)  
    {/each}
    {/if}
    
    ```statblock
    {resource.5eStatblockYaml}
    ```
    ^statblock
    {#if resource.environment }
    
    ## Environment
    
    {resource.environment}
    {/if}
    
</p>
</details>

**Comment by ebullient** [comment]
> Looks like it breaks while while processing the images in my template. I included the log and one of the templates that causes the crash below.

Thanks for the example template & exception. I use the same/similar field, and did not have that issue, but I'll try again to make sure.

As an aside, you'll want to double check how you're including the images & description in the template above, as I think you drop the first image if a description is present. The reference template for images tries to split things: the first image, then the description, then the rest of the images (if there is more than one).

```
{#if resource.description }
{#if resource.fluffImages && resource.fluffImages.size > 0 }{#let first=resource.fluffImages.get(0)}
![{first.title}]({first.vaultPath}#right)  
{/let}{/if}
{resource.description}

{#each resource.fluffImages}{#if it_index != 0 }
![{it.title}]({it.vaultPath}#center)  
{/if}{/each}
{#else}
{#each resource.fluffImages}
![{it.title}]({it.vaultPath}#center)  
{/each}
{/if}
```

If you want to show all images after the description, you can simplify: 

```
{#if resource.description }
{resource.description}

{/if}
{#each resource.fluffImages}
![{it.title}]({it.vaultPath}#center)  
{/each}
```

(mess with whitespace before/after as you wish)

**Comment by ebullient** [comment]
blargh. I really need to do the thing to hide emoji for terminal/command lines that can't handle them. That said, the above suggests that the snapshot is older. I fixed "Source KftGV is unknown" awhile ago. I think the jitpack build is (or was) broken. 

Will push a new release shortly.

**Comment by ebullient** [comment]
Released.. try 2.0.2

**Comment by TehMightyPotato** [comment]
Works like a charm! Thank you very much!
