### ISSUE TITLE
2.0.5 Bug: PF2E Tools Sources not Queryable from TTRPG Convert

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/ttrpg-convert-cli#165]
## Conditions
- macOS Ventura
- Fresh clone and build
- Also Tried Prebuilt Release
- Fresh clone of Pf2etools

### Without Defined Sources
_This Should default to CRB, and Has Prior_.

```bash
./ttrpg-convert \                                
-g pf2e \
--index \
-o Dungeon-Fools \
Pf2eTools/data
✅ finished reading config.
⏱️ Reading /Users/sigrunshepherd/Git/Example/Pf2eTools/data
java.lang.NullPointerException
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.keyIsIncluded(Pf2eIndex.java:243)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.isIncluded(Pf2eIndex.java:250)
	at dev.ebullient.convert.tools.pf2e.JsonTextReplacement.linkify(JsonTextReplacement.java:317)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.prepareTrait(Pf2eIndex.java:141)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.addToIndex(Pf2eIndex.java:98)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndexType.lambda$withArrayFrom$1(Pf2eIndexType.java:95)
	at java.base@17.0.5/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndexType.withArrayFrom(Pf2eIndexType.java:95)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.importTree(Pf2eIndex.java:78)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.importTree(Pf2eIndex.java:26)
	at dev.ebullient.convert.io.Tui.readFile(Tui.java:347)
	at dev.ebullient.convert.io.Tui.readToolsDir(Tui.java:402)
	at dev.ebullient.convert.io.Tui_ClientProxy.readToolsDir(Unknown Source)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:198)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:263)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:283)
	at dev.ebullient.convert.RpgDataConvertCli_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Prebuilt with Defined Sources in Json

```bash
./ttrpg-convert \
-g pf2e \
--index \
-o Dungeon-Fools \
-c pf2e.json \
> Pf2eTools/data/
✅ finished reading config.
⏱️ Reading /Users/sigrunshepherd/Git/Example/Pf2eTools/data
java.lang.NullPointerException
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.keyIsIncluded(Pf2eIndex.java:245)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.isIncluded(Pf2eIndex.java:250)
	at dev.ebullient.convert.tools.pf2e.JsonTextReplacement.linkify(JsonTextReplacement.java:317)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.prepareTrait(Pf2eIndex.java:141)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.addToIndex(Pf2eIndex.java:98)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndexType.lambda$withArrayFrom$1(Pf2eIndexType.java:95)
	at java.base@17.0.5/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndexType.withArrayFrom(Pf2eIndexType.java:95)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.importTree(Pf2eIndex.java:78)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.importTree(Pf2eIndex.java:26)
	at dev.ebullient.convert.io.Tui.readFile(Tui.java:347)
	at dev.ebullient.convert.io.Tui.readToolsDir(Tui.java:402)
	at dev.ebullient.convert.io.Tui_ClientProxy.readToolsDir(Unknown Source)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:198)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:263)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:283)
	at dev.ebullient.convert.RpgDataConvertCli_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

#### Json Zipped Up

[pf2e.json.zip](https://github.com/ebullient/ttrpg-convert-cli/files/11898932/pf2e.json.zip)

## Java Jar
Source Error with Defined Sources

```bash
java -jar ttrpg-convert-cli/target/ttrpg-convert-cli-299-SNAPSHOT-runner.jar \
-g pf2e \
--index \
-s CRB \         
> -o Dungeon-Fools \
> Pf2eTools/data 
✅ finished reading config.
⏱️ Reading /Users/sigrunshepherd/Git/Example/Pf2eTools/data
java.lang.NullPointerException: Cannot invoke "dev.ebullient.convert.tools.pf2e.Pf2eSources.getBookSources()" because "sources" is null
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.keyIsIncluded(Pf2eIndex.java:245)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.isIncluded(Pf2eIndex.java:250)
	at dev.ebullient.convert.tools.pf2e.JsonTextReplacement.linkify(JsonTextReplacement.java:317)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.prepareTrait(Pf2eIndex.java:141)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.addToIndex(Pf2eIndex.java:98)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndexType.lambda$withArrayFrom$1(Pf2eIndexType.java:95)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndexType.withArrayFrom(Pf2eIndexType.java:95)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.importTree(Pf2eIndex.java:78)
	at dev.ebullient.convert.tools.pf2e.Pf2eIndex.importTree(Pf2eIndex.java:26)
	at dev.ebullient.convert.io.Tui.readFile(Tui.java:347)
	at dev.ebullient.convert.io.Tui.readToolsDir(Tui.java:402)
	at dev.ebullient.convert.io.Tui_ClientProxy.readToolsDir(Unknown Source)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:198)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:263)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:283)
	at dev.ebullient.convert.RpgDataConvertCli_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**Comment by ebullient** [comment]
reproduced. so now to find out why...
