### ISSUE TITLE
🐛 NPE on today's snapshot

### ISSUE THREAD

**Issue by paulsnoops** [ebullient/ttrpg-convert-cli#197]
Starting fresh using today's snapshot produced an NPE as follows:

> ? An error occurred: Cannot invoke "com.fasterxml.jackson.databind.node.ObjectNode.set(String, com.fasterxml.jackson.databind.JsonNode)" because "targetNode" is null.
Run with --debug for details.
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.node.ObjectNode.set(String, com.fasterxml.jackson.databind.JsonNode)" because "targetNode" is null
        at dev.ebullient.convert.tools.dnd5e.JsonSourceCopier.lambda$mergeFields$8(JsonSourceCopier.java:356)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at dev.ebullient.convert.tools.dnd5e.JsonSourceCopier.mergeFields(JsonSourceCopier.java:356)
        at dev.ebullient.convert.tools.dnd5e.JsonSourceCopier.mergeNodes(JsonSourceCopier.java:193)
        at dev.ebullient.convert.tools.dnd5e.JsonSourceCopier.cloneOrCopy(JsonSourceCopier.java:106)
        at dev.ebullient.convert.tools.dnd5e.JsonSourceCopier.copyAndMergeRace(JsonSourceCopier.java:78)
        at dev.ebullient.convert.tools.dnd5e.JsonSourceCopier.handleCopy(JsonSourceCopier.java:47)
        at dev.ebullient.convert.tools.dnd5e.Tools5eIndex.prepare(Tools5eIndex.java:300)
        at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:228)
        at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:263)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:283)
        at dev.ebullient.convert.RpgDataConvertCli_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

For converting to complete.

Installed via JBang and ran the converter but it stops after the above error.

## Configuration
- **OS**: Windows with Jbang

**Sources**:
- enabled sources: Everything from the SourceMap testing purposes :)

**Comment by ebullient** [comment]
This one should be fixed (as of last night). But JitPack could be borked.

**Comment by ebullient** [comment]
You can download the jar directly, and use `java -jar ...`, or update the jbang install with 

```
jbang app install --name ttrpg-convert-ss --force --fresh https://github.com/ebullient/ttrpg-convert-cli/releases/download/299-SNAPSHOT/ttrpg-convert-cli-299-SNAPSHOT-runner.jar
```

**Comment by paulsnoops** [comment]
This seems to be working now, thanks!
