### ISSUE TITLE
🐛 Issue with ttrpg-convert and 2014 dnd 5etools

### ISSUE THREAD

**Issue by Penthious** [ebullient/ttrpg-convert-cli#584]
When running  `ttrpg-convert --index -o dm -s DMG ../5etools-2014-src/data --debug`

Where 5etools-2014-src is https://github.com/5etools-mirror-3/5etools-2014-src/releases/tag/v1.210.11 or greater

I get a nil pointer exception.

Using v1.210.10 the cli command works just fine

A clear and concise description of what you expected to happen. A text snippet is helpful.

```
🔧 4 subraces found for race|genasi|mpmm
🔧 	race|genasi (earth)|mpmm :: subrace|genasi (earth)|genasi|mpmm
🔧 	race|genasi (air)|mpmm :: subrace|genasi (air)|genasi|mpmm
🔧 	race|genasi (fire)|mpmm :: subrace|genasi (fire)|genasi|mpmm
🔧 	race|genasi (water)|mpmm :: subrace|genasi (water)|genasi|mpmm
[ 🛑 ERR] An error occurred: NullPointerException.

Run with --debug for details.
java.lang.NullPointerException
	at dev.ebullient.convert.tools.dnd5e.Tools5eJsonSourceCopier.doModProp(Tools5eJsonSourceCopier.java:322)
	at dev.ebullient.convert.tools.JsonSourceCopier.doModProp(JsonSourceCopier.java:185)
	at dev.ebullient.convert.tools.JsonSourceCopier.doMod(JsonSourceCopier.java:151)
	at dev.ebullient.convert.tools.JsonSourceCopier.applyMods(JsonSourceCopier.java:141)
	at dev.ebullient.convert.tools.dnd5e.Tools5eJsonSourceCopier.mergeNodes(Tools5eJsonSourceCopier.java:258)
	at dev.ebullient.convert.tools.dnd5e.Tools5eJsonSourceCopier.mergeNodes(Tools5eJsonSourceCopier.java:26)
	at dev.ebullient.convert.tools.JsonSourceCopier.handleCopy(JsonSourceCopier.java:73)
	at dev.ebullient.convert.tools.dnd5e.Tools5eIndex.prepare(Tools5eIndex.java:417)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:238)
	at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:273)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:285)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

## Configuration

- **OS**: MacOS M4
```
ttrpg-convert --version

ttrpg-convert version 2.3.18
Git commit: ed56f76
Build time: 2024-07-27T02:01:26Z
```

**Sources**:
- enabled sources
- custom templates (attach if possible)

**Comment by ebullient** [comment]
[See this solution](https://github.com/ebullient/ttrpg-convert-cli/issues/565#issuecomment-2466489526)
